### ISSUE TITLE
Is .Net Core 3 supported?

### ISSUE THREAD

**Issue by hussain1368** [ErikEJ/EntityFramework.SqlServerCompact#583] opened 2020-12-22 13:39 UTC
The title says everything. Does this package support .Net Core 3.1? I am building a WPF project in .net core 3.1

**Comment by ErikEJ** [comment] 2020-12-22 13:41
No, it only works on .NET Framework with EF Core 2.2

Duplicate of #576

**Closed by ErikEJ** 2020-12-22 13:41 UTC
