### ISSUE TITLE
UseSqlCe not found in latest version

### ISSUE THREAD

**Issue by Luk164** [ErikEJ/EntityFramework.SqlServerCompact#580] opened 2020-04-20 17:30 UTC
When I am using the latest version of this package the UseSqlCe function is not found, I have to go a few versions back to make it work again.

**Comment by ErikEJ** [comment] 2020-04-20 17:33
Sounds unlikely .. which versions?

**Comment by Luk164** [comment] 2020-04-20 17:35
2.1.2.1 Sees it, 2.2.0.7 does not, did not test version in between. Though it looks like it is not a fit for my project anyway.

**Comment by Luk164** [comment] 2020-04-20 17:37
For context I currently support MSSQL and MYSQL, and I wanted a built in DB so the user does not have to install either DB engine to make the app work. The SQLite was bitching about unsupported funtions in migration so I wanted to see if this works better,

**Comment by ErikEJ** [comment] 2020-04-20 17:39
More migration operations are supported by this compared to SQLite.

**Comment by Luk164** [comment] 2020-04-20 17:40
Yeah, but it still did not work, so I think I will abandon the idea of embedded database...

**Comment by Eonasdan** [comment] 2020-05-14 21:50
I had this problem also and had to go back to 2.2.0

**Comment by ErikEJ** [comment] 2020-05-15 06:17
I am unable to reproduce, please share a project.
```

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFrameworkCore.SqlServerCompact40" version="2.2.0.7" targetFramework="net472" />
  <package id="EntityFrameworkCore.SqlServerCompact40.Core" version="2.2.0.7" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Analyzers" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Caching.Memory" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" targetFramework="net472" />
  <package id="Remotion.Linq" version="2.2.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net472" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net472" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.0" targetFramework="net472" />
  <package id="System.Interactive.Async" version="3.2.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.1" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.1" targetFramework="net472" />
</packages>

```

**Comment by ErikEJ** [comment] 2020-05-26 12:19
Closing - not able to repro -feel free to re-open if you can provide a repro project.

**Comment by Luk164** [comment] 2020-05-26 14:05
@ErikEJ Oh, sorry for not replying. The project is a part of a bachelors degree work, so I have to wait until I can turn it in before I make anything available. Once that is done I can give all the access you need.

**Comment by stonesbg** [comment] 2020-07-06 08:41
@Luk164 Try adding in the "EntityFrameworkCore.SqlServerCompact40.Core".  When I added just the package "EntityFrameworkCore.SqlServerCompact40" I noticed that the Core package was not automatically pulled in (..for me at least).  You will also need the Microsoft.SqlServer.Compact. At least in my case I now have access to the UseSqlCe.  Hope that helps

**Comment by Luk164** [comment] 2020-07-06 08:46
Thanks, will give it a go when I have some extra time. Could it be set to pull this automatically though? It would cause a lot less confusion.

**Comment by ErikEJ** [comment] 2020-07-06 08:57
@Luk164 They are pulled in automatically, if you install the https://www.nuget.org/packages/EntityFrameworkCore.SqlServerCompact40/ package.

**Comment by Luk164** [comment] 2020-07-07 07:56
@ErikEJ Ok, I will take a look at that one. Thank you

**Closed** 2020-08-05 12:22 UTC
